export const COUNTRIES = {
  DE: "Germany",
  US: "United States",
  KZ: "Kazakhstan",
  UZ: "Uzbekistan",
  FR: "France",
  IT: "Italy",
  ES: "Spain",
  CN: "China",
  IN: "India",
  JP: "Japan",
  GB: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
  BR: "Brazil",
  RU: "Russia",
  MX: "Mexico",
  ZA: "South Africa",
  NG: "Nigeria",
  EG: "Egypt",
  AR: "Argentina",
  UA: "Ukraine",
  NL: "Netherlands",
  SE: "Sweden",
  TR: "Turkey",
  PL: "Poland",
  CH: "Switzerland",
  NO: "Norway",
  DK: "Denmark",
  BE: "Belgium",
  FI: "Finland",
  AT: "Austria",
  IE: "Ireland",
  CZ: "Czech Republic",
  HU: "Hungary",
  SK: "Slovakia",
  RO: "Romania",
  BG: "Bulgaria",
  AF: "Afghanistan",
  SA: "Saudi Arabia",
  IL: "Israel",
  IR: "Iran",
  PK: "Pakistan",
  BD: "Bangladesh",
  TH: "Thailand",
  VN: "Vietnam",
  MY: "Malaysia",
  SG: "Singapore",
  ID: "Indonesia",
  PH: "Philippines",
  MD: "Moldova",
  BY: "Belarus",
  HR: "Croatia",
  SI: "Slovenia",
  RS: "Serbia",
  ME: "Montenegro",
  AL: "Albania",
  MK: "North Macedonia",
  IS: "Iceland",
  LU: "Luxembourg",
  LI: "Liechtenstein",
  MT: "Malta",
  CY: "Cyprus",
  AE: "United Arab Emirates",
  TT: "Trinidad and Tobago",
  HK: "Hong Kong",
  LV: "Latvia",
  LT: "Lithuania",
  EE: "Estonia",
  TZ: "Tanzania",
  KE: "Kenya",
} as const;

export default function getCountryNameByCode(code: string) {
  const res = COUNTRIES[code as keyof typeof COUNTRIES];
  return res ? res : code;
}
